### ISSUE TITLE
Herintrede van vroegtijdige schoolverlaters

### ISSUE THREAD

**Issue by dimitrivanbaelen** [provinciesincijfers/data-wishlist#1]
Zopas is een studie verschenen over het aantal vroegtijdige schoolverlaters die zich binnen 5 jaar inschrijven in één van de kanalen om alsnog hun diploma secundair onderwijs te halen (onderste blok op https://www.onderwijs.vlaanderen.be/nl/nl/samen-tegen-schooluitval/vroegtijdig-schoolverlaten/cijfers-over-schooluitval).  De cijfers worden gepresenteerd op Vlaams niveau, weet er iemand of de cijfers ook beschikbaar kunnen gemaakt worden op een lager regionaal niveau?

**Comment by joostschouppe** [comment]
Na eerste screening door @VickyVB lijkt het dat de aantallen wellicht te klein zijn om interessant te zijn op gemeenteniveau
