### ISSUE TITLE
Aantal verschillende nationaliteiten

### ISSUE THREAD

**Issue by dimitrivanbaelen** [provinciesincijfers/data-wishlist#10]
Een vraag die bij ons geregeld gesteld wordt, is het aantal verschillende nationaliteiten.  Dat is terug te vinden in de Lokale Inburgerings- en IntegratieMonitor (voor Mechelen hier te vinden: https://www.statistiekvlaanderen.be/sites/default/files/docs/LIIM-Mechelen.pdf), maar ik vind hier niet meteen een tijdsreeks over terug.  Kan dit opgenomen worden in Swing?

**Comment by joostschouppe** [comment]
Dit staat al lang op onze planning. Ik kan er nog geen timing op zetten, maar ik neem aan dat het binnen enkele maanden mee wordt opgenomen.

**Comment by joostschouppe** [comment]
Dit staat al even online / in connector
