### ISSUE TITLE
Onderwerp "totaal belastingaangiften"

### ISSUE THREAD

**Issue by isabellevanderheyden** [provinciesincijfers/data-wishlist#11]
In zowel “provincies in cijfers” als “Limburg in cijfers” staat dit onderwerp in de databank onder de code 1203_aangiften_tot
In de ons via de connector aangeleverde onderwerpen staat dit onderwerp er echter niet tussen, wel dna_v1203_tot_aant_aang maar dat is niet hetzelfde onderwerp…

Kan dit ontbrekend onderwerp (en aanverwanten) nog toegevoegd worden in de connector?

**Comment by joostschouppe** [comment]
We willen nog tegen het einde van het jaar dit "ontbrekende onderwerp" vervangen door hetgeen jullie wel al krijgen. Het aantal dat nog ontbreekt voor 2017 wordt ook dit jaar nog toegevoegd. We hebben destijds gekozen om énkel de data van de interstedelijke aanvraag door te sluiten, om verwarring te vermijden.

**Comment by joostschouppe** [comment]
De data-levering is uitgesteld, en daarna deels opgeleverd, met de mededeling dat een volledige update pas kan ten vroegste juni 2020.

**Comment by joostschouppe** [comment]
Dit thema is inmiddels volledig geherorganiseerd
