### ISSUE TITLE
Cijfers sociale huisvesting op sectorniveau

### ISSUE THREAD

**Issue by anneliesvs** [provinciesincijfers/data-wishlist#14]
De cijfers van sociale huisvesting zijn momenteel enkel beschikbaar op gemeenteniveau.
Kunnen we de cijfers ook op sectorniveau krijgen?

**Comment by joostschouppe** [comment]
Dit zou eraan komen. Er volgt in de loop van deze week een stavaza

**Comment by StefanieWVL** [comment]
De data voor de sociale huisvestingsmaatschappijen zijn vandaag opgeladen in PinC op statistisch sectorniveau (toestand 31/12/2018 - weergegeven als 2019)
De adresgegevens van de sociaal verhuurkantoren werden opgevraagd (en zijn op komst) en na verwerking zullen deze ook toegevoegd worden aan PinC.

**Comment by StefanieWVL** [comment]
De data van de sociaal verhuurkantoren op adresniveau zijn toegekomen. Moeten nu in Gis verwerkt worden en kunnen daarna op stst sec niveau opgeladen worden in Pinc.

**Comment by joostschouppe** [comment]
Vraag van @mehtap19:

een nieuwe vraag van mijn kant: we zien dat de sociale huurwoningen SHM op statsec niveau beschikbaar zijn terwijl die van SVK op stadsniveau zitten.

Hierdoor kunnen we de data op wijkniveau niet met elkaar vergelijken.

Komen de data SVK op statsec niveau? Zo ja, heb je zicht op de timing?

**Comment by StefanieWVL** [comment]
Ik hoop dit in mei te kunnen doen. Ga in principe volgende week mijn 2de scherm halen. Heb ik hiervoor wel nodig.

**Comment by StefanieWVL** [comment]
Data SVK werd op stat sec toegevoegd:  huurwoningen SVK, eengezinswoningen SVK en appartementen SVK. 
Ook totaal sociale huisvesting (SHM+SVK) kan dus nu berekend worden op stat sec.

**Comment by mehtap19** [comment]
@joostschouppe kan deze dataset opnieuw in de laatste dump toegevoegd worden? We zouden ze willen opnemen in de wijkmonitor die we aan het ontwikkelen zijn.

**Comment by joostschouppe** [comment]
Ik versta je vraag niet. Als @StefanieWVL de data in dezelfde onderwerpen heeft toegevoegd, dan stromen ze dit weekend automatisch naar jullie door.

**Comment by mehtap19** [comment]
@joostschouppe is in orde ;)
