### ISSUE TITLE
cijfers LIIM

### ISSUE THREAD

**Issue by BartDaemen** [provinciesincijfers/data-wishlist#15]
Kunnen gegevens uit de de Lokale Inburgerings- en Integratiemonitor (LIIM) opgenomen worden. 
De LIIM vat voor iedere gemeente de cijfers over migratie, integratie en inburgering samen. De monitor helpt lokale besturen zo om hun integratiebeleid te plannen.

Zou meerwaarde zijn om gegevens die nog niet in databank zitten, daar op te nemen, zodat niet doorverwezen moet worden naar apart pdf-document / en gegevens gecombineerd kunnen worden met andere.

Veel gegevens zitten op één of andere manier al in databank (met andere bronnen of andere definities). Heb in inhoudstafel als bijlage gemarkeerd welke voor ons een meerwaarde zouden zijn...

Gr, 

Bart

**Comment by joostschouppe** [comment]
Bart, de bijlage is weggevallen

**Comment by StefanJacques** [comment]
[Indicatoren_LIIM_extra.xlsx](https://github.com/provinciesincijfers/data-wishlist/files/4324829/Indicatoren_LIIM_extra.xlsx)

hoe kunnen we dit behandelen op komende redactiegroep ?

Aanvullend: deze vraag komt nu van Bart, maar (een deel van) deze indicatoren zijn mogelijks ook interessant voor het diversiteitsrapport.
Agentschap inburgering is bijvoorbeeld ook vragende partij om leefloners volgens nationaliteit op te nemen.

**Comment by StefanJacques** [comment]
antwoorden redactiegroep toegevoegd: 
[Indicatoren_LIIM_extra_antwoorden_redactiegroep.xlsx](https://github.com/provinciesincijfers/data-wishlist/files/4443872/Indicatoren_LIIM_extra_antwoorden_redactiegroep.xlsx)

**Comment by StefanJacques** [comment]
Valerie heeft terug contact opgenomen met Bart. Hij zal de vraag over de inburgeraars breder stellen via de centrumsteden. Wordt (misschien) vervolgd.

**Comment by joostschouppe** [comment]
@BartDaemen moesten we hier nu nog iets mee doen?

**Comment by BartDaemen** [comment]
Mag afgesloten worden - volgen inburgering zelf intern op
