### ISSUE TITLE
Gebruiksgegevens elektrische laadpalen

### ISSUE THREAD

**Issue by dimitrivanbaelen** [provinciesincijfers/data-wishlist#16]
Kunnen we van fluvius data krijgen (bij voorkeur per laadpaal) van het aantal laadbeurten, aantal unieke gebruikers en totale energieopname per maand en per jaar?

**Comment by joostschouppe** [comment]
Dimitri volgt dit tot verder bericht rechtstreeks op met Kris van Klimaat provincie Antwerpen.
