### ISSUE TITLE
kunnen de kaarten van PinC gedownload worden als shape-files :-)?

### ISSUE THREAD

**Issue by StefanieWVL** [provinciesincijfers/data-wishlist#17]
Er kwam zonet een vraag binnen van een gebruiker: kunnen de kaarten in PinC gewdowload worden als shape-file ;-)

**Comment by joostschouppe** [comment]
Da's eentje voor de FAQ.
Neen, niet als dusdanig.
Je kan wel de data afhalen, en bij GEBIEDSINDELINGEN>gebiedscode de juiste unieke code opvragen.
We gebruiken standaard unieke codes, dus in vele gevallen hebben mensen zelf al een goede shapefile om aan te koppelen.
Het staat wel al een tijdje op mijn planning om zo'n algemene shapefile per gebiedsniveau aan te bieden via de metadata van de gebiedsniveaus.
De huidige data zélf als shapefile meegeven heeft niet zo veel zin en zal wellicht nooit kunnen.
Wel kunnen mensen vragen om een WMS te voorzien indien ze een bepaalde kaart vaak nodig hebben.

**Comment by joostschouppe** [comment]
Dit kan nu wel, via https://github.com/provinciesincijfers/gebiedsniveaus/tree/master/data_voor_swing/shapefiles

**Comment by StefanieWVL** [comment]
Als ik op bovenstaande link klik, staat er dat die files verwijderd zijn ...

**Comment by joostschouppe** [comment]
Nee, er staat dat de laatste actie in die map is dat ik wat dingen verwijderd heb :)
Maar de relevante dingen staan daar vlak onder!
Maar om ze te downloaden is het veel handiger om heel de repository te downloaden https://github.com/provinciesincijfers/gebiedsniveaus/archive/master.zip ; die link vind je op https://github.com/provinciesincijfers/gebiedsniveaus achter de groene knop "Code"
