### ISSUE TITLE
detailcijfers koopstromen

### ISSUE THREAD

**Issue by isabellevanderheyden** [provinciesincijfers/data-wishlist#18]
@joostschouppe We zijn op zoek naar de gegevens achter de kaarten in het rapport Detailhandel, specifiek het deel Koopstromen. De kleuren op de kaart verwijzen naar een categorie, onze collega's willen graag de exacte cijfers zien. Indien mogelijk zowel voor Genk, Hasselt als Maasmechelen en voor de verschillende categoriëen. mvg

**Comment by joostschouppe** [comment]
Dat kan. Hiervoor kan je je account (cs_genk, cs_ aalst, ...) op de databank gebruiken, vervolgens kijken bij INTERN / Project Detailhandel. Let wel: het zijn gemodelleerde cijfers, dus "exact" mag je ze alvast niet interpreten.
