### ISSUE TITLE
Bijkomend gebiedsniveau: woontypologieën

### ISSUE THREAD

**Issue by dimitrivanbaelen** [provinciesincijfers/data-wishlist#19]
Steunpunt wonen heeft op basis van een multifactoranalyse een indeling van de statistische sectoren in 16 woontypologieën gemaakt.  Kan dit als een nieuw gebiedsniveau worden toegevoegd?  Meer info op https://steunpuntwonen.be/Documenten_2016-2020/Onderzoek_Werkpakketten/WP_5_Werking_van_de_woningmarkt/WP5-2_TOELICHTING  Daar vind je onder andere een excelbestand met de toewijzing statistische sector - cluster.

**Comment by joostschouppe** [comment]
We hebben het bij wijze van experiment een tijd geleden ingelezen als label-onderwerp ([voorbeelden](https://provincies.incijfers.be//jive?workspace_guid=ba1cc2ca-3b20-47ec-ad5d-2aa3b40752be)). De reacties in de D&A teams was echter niet zo enthousiast. Waarom zou je het als gebiedsniveau willen kunnen gebruiken?

**Comment by dimitrivanbaelen** [comment]
Hallo Joost,

Bij ons zijn een aantal mensen binnen Duurzame Ontwikkeling en Energie geïnteresseerd, om bijvoorbeeld na te gaan of er verbanden zijn met premies voor zonnepanelen en isolatie e.d. en om na te gaan of er specifieke gebieden zijn die interessant zijn om op te focussen.

**Comment by joostschouppe** [comment]
Kan je anders eens wat testen, eventueel op basis van die label-variabele? Alleszins hebben wij geen premies tot op statsec niveau, dus ben er niet direct veel mee als gebiedsniveau denk ik.

**Comment by dimitrivanbaelen** [comment]
Hallo Joost,

Is er een manier waarop ik dan deze indeling kan gebruiken om bijvoorbeeld te kijken wat de bevolkingsdichtheid is voor elk van deze clusters?  Of is dat dan enkel te doen door de indicator op StatSec-niveau op te vragen, er de labelvariabele bijzetten, en dan via download naar excel en pivoteren?

**Comment by joostschouppe** [comment]
Klopt, ik vrees dat dat de enige manier is, zoals het nu ingeladen is

**Comment by joostschouppe** [comment]
Dimitri, leeft deze vraag nog?
