### ISSUE TITLE
VDAB rapport schoolverlaters - onderwerpen toevoegen in Swing?

### ISSUE THREAD

**Issue by liesbetvandriessche** [provinciesincijfers/data-wishlist#20]
De VDAB heeft haar nieuw rapport over schoolverlaters gepubliceerd samen met een interactief dashboard. Is het mogelijk om de deze data op te nemen in Swing Studio?
https://www.vdab.be/schoolverlatersrapport
https://www.vdab.be/sites/web/files/doc/schoolverlaters/schoolverlatersrapport2019.pdf
https://www.vdab.be/trendsdoc/schoolverlaters/detail/default.shtml

**Comment by VickyVB** [comment]
Inderdaad zeer interessant. Ik bekijk dit  maandag 24.02 en zie wat kan opgenomen worden in PinC.

**Comment by mehtap19** [comment]
Hey @VickyVB weet je al iets meer over deze issue? Gaan die in de connector gezet worden? De nieuwe cijfers zijn zonet gepubliceerd en vroegen ons af of wij ze via de connector konden publiceren.

**Comment by VickyVB** [comment]
Ik heb deze cijfers inderdaad bekeken en opgeladen in PinC. Ze zijn echter (gebiedsdekkend) enkel beschikbaar op arrondissementeel niveau. We hebben bijgevolg niet direct plannen om ze extern te plaatsen of in de connector te zetten.

**Comment by liesbetvandriessche** [comment]
@VickyVB bedankt om te onderzoeken

**Comment by AmelieLeuven** [comment]
Hallo, ondertussen zijn we weer een tijdje verder. 
Ik zie dat op https://www.vdab.be/trendsdoc/schoolverlaters/detail/default.shtml heel veel data beschikbaar is voor Leuven. Misschien is dat ook wel zo voor andere gebieden? Mijn collega kreeg dit antwoord terug van de arbeidsmarktregisseur van de VDAB op haar vraag naar data en waarom Leuven uigegrijsd lijkt op de website. 
"De grijze kleur is louter opmaak om het verschil duidelijk te maken tussen de arrondissementen en de centrumsteden in de keuzelijst. De schoolverlatersresultaten voor centrumstad Leuven zijn zeker correct in de toepassing. Het is belangrijk om weten dat de cijfers voor de centrumsteden enkel bevraagbaar zijn tot op studieniveau aangezien de indeling per studiegebied en -richting een te klein aantal schoolverlaters heeft om zinvolle conclusies te trekken."
Is het zinvol dat jullie dit nog eens bekijken of maken we zelf indicatoren aan best?

Amélie
