### ISSUE TITLE
Absolute cijfers risicokenmerken onderwijs

### ISSUE THREAD

**Issue by BartDaemen** [provinciesincijfers/data-wishlist#23]
Beste, 

Op dit moment zitten enkel de % van de afzonderlijke risicokenmerken onderwijs in de connector (onderwijs > leerplichtonderwijs > basisonderwijs / secundair onderwijs > risicokenmerken). 
Is het mogelijk om ook de absolute cijfers toe te voegen? Beleidsmatig relevant om wijken te selecteren om bepaalde acties op te zetten (bijvoorbeeld als we focussen op 5 wijken, welk percentage van alle lln met specifiek kenmerk kunnen we dan theoretisch bereiken).

Met vriendelijke groeten, 

Bart

**Comment by joostschouppe** [comment]
Komt in orde.
Ben je overigens zeker dat je ze niet hebt? Ik dacht dat de connector sowieso ook onderwerpen meeneemt die nodig zijn voor formule-onderwerpen, ZELFS als deze niet in onze themaboom voor de Connector zitten.

**Comment by BartDaemen** [comment]
Klopt! Heb ze gevonden in een ander mapje. Vraag opgelost dus!
