### ISSUE TITLE
cijfers IGO op wijkniveau?

### ISSUE THREAD

**Issue by anneliesvs** [provinciesincijfers/data-wishlist#24]
Kunnen de cijfers over ouderen met een inkomensgarantie (IGO+GIB) ook op wijkniveau ontsloten worden?

**Comment by veravandestraat** [comment]
De cijfers over ouderen met een inkomensgarantie (IGO+GIB) die we binnenkrijgen van de federale pensioendienst zijn op postcode, dus enkel wanneer de postcode samenvalt met een wijk is het mogelijk om de cijfers op wijkniveau te geven.
