### ISSUE TITLE
kubus werkende inwoners

### ISSUE THREAD

**Issue by mehtap19** [provinciesincijfers/data-wishlist#25]
@joostschouppe kunnen de platte onderwerpen mbt kubus werkende inwoners naar geslacht, leeftijd, sector en statuut (dna_werk_leeft_geslacht_sector_statuut) in de connector gezet worden? Ze staan in PinC

Bedankt.

**Comment by joostschouppe** [comment]
toegevoegd; komen er dit weekend bij. Onder ARBEIDSMARKT > Arbeidsmarktpositie van bevolking op arbeidsleeftijd (15-64 jaar)
