### ISSUE TITLE
Arbeidsregime loontrekkenden

### ISSUE THREAD

**Issue by mehtap19** [provinciesincijfers/data-wishlist#27]
@joostschouppe dankzij de kubus werkenden kunnen we heel wat detailinformatie mbt werken snel opvragen. 
![afbeelding](https://user-images.githubusercontent.com/45229639/86253155-6dde1600-bbb4-11ea-9cb6-533441f16595.png)

Het zou interessant zijn mocht die uitgebreid worden met een extra dimensie arbeidsregime voor loontrekkenden. Die gegevens zijn ook beschikbaar. Platte onderwerpen zijn ook zeer welkom!

Alvast bedankt om dit te bekijken.

**Comment by joostschouppe** [comment]
@Lievendr ; bekijk jij eens of dit haalbaar is?

**Comment by Lievendr** [comment]
Joost,
ik snap de vraag niet zo goed. de cijfers die ik terugvind op Steunpunt werk gaan in beste geval over geslacht x leeft x arbeidsregime x sector tot 2017. Vicky heeft arbeid uitgetekend i.s.m. POM Limburg. ik weet dus niet of de werkgroep hier niet eerst over moet gaan vooraleer ik die kubus eventueel oplaad? Ik stel voor dat Vicky haar idee hier eerst over geeft?

**Comment by joostschouppe** [comment]
Lieven, lijkt me inderdaad goed om het met Vicky en de werkgroep te bekijken

**Comment by VickyVB** [comment]
De werkenden-kubus waarnaar je verwijst, de werkenden **naar woonplaats**, is in zijn geheel overgenomen van het Steunpunt Werk. Er wordt hier geen extra dimensie voor arbeidsregime voor de loontrekkenden gegeven (cfr. https://www.steunpuntwerk.be/node/2787).
Het Steunpunt Werk heeft wel arbeidsregime gegevens over de werkgelegenheid, de werkenden **naar werkplaats**. Deze gegevens zijn echter niet opgenomen in PinC. Er werd immers voor gekozen om in het luik van de werkgelegenheid, de arbeidsplaatsen, de gegevens van RSZ enerzijds en RSVZ anderzijds te gebruiken. In de huidige RSZ-gegevens zit daar de het arbeidsregime nog niet bij. Momenteel werken we echter aan een nieuwe, uitgebreide RSZ aanvraag. Daarin zijn, voor de loontrekkende werkgelegenheid, bijkomend opgenomen: sector, dimensieklasse van de vestiging, geslacht, type werknemer (arbeider/bediende/ambtenaar) en ook het arbeidsregime (voltijds/deeltijds/speciaal). Ik schat dat deze update tegen het einde van 2020 klaar zal zijn voor publicatie op PinC.
