### ISSUE TITLE
data onderwijs

### ISSUE THREAD

**Issue by anneliesvs** [provinciesincijfers/data-wishlist#28]
Is er al een timing voor de nieuwe cijfers van onderwijs?
Op dataloep is schooljaar 2018-2019 al beschikbaar.

**Comment by VickyVB** [comment]
Voor PinC wordt er nog een bijkomende correctie van de de adressen gedaan door de verschillende steunpunten D&A.
We hebben deze te corrigeren gegevens vorige week ontvangen. Momenteel zitten we dus op het schema van de vorige jaren. Ik verwacht dan ook dat de gegevens 2018-2019 beschikbaar zullen zijn in de 2 de helft van september/ begin oktober.
