### ISSUE TITLE
Inkomende pendel - issue met doorstroming connector

### ISSUE THREAD

**Issue by BartDaemen** [provinciesincijfers/data-wishlist#29]
Beste, 

Er lijkt iets fout te lopen met de doorstroom in connector centrumsteden van de gegevens van woon-werkpendel. Ik krijg totaalcijfers voor inkomende pendel en geen pendel, zie [url](https://hasselt.incijfers.be//jive?workspace_guid=19e04723-6742-49e0-990f-a247a6f4f87e). Probleem doet zich voor vanaf jaar 2008.

Op de provincies.incijfers.be loopt wel alles correct.

Is er iets mis met de doorstroom gegevens, of moet ik fout hier intern zoeken?

**Comment by joostschouppe** [comment]
Inderdaad, als je vergelijkt met https://provincies.incijfers.be//jive?workspace_guid=c21561e7-bac2-4a0c-9c1f-1790f51cfc00 dan zijn dat heel andere cijfers. Ik vraag het na bij Richard.

![afbeelding](https://user-images.githubusercontent.com/10122639/88283325-775a2a00-cceb-11ea-995e-943468bc1d56.png)

**Comment by joostschouppe** [comment]
Richard heeft het probleem geanalyseerd. Effectief een Connector-probleem. Wellicht bij volgende run in orde!

**Comment by joostschouppe** [comment]
gecontroleerd en is in orde
