### ISSUE TITLE
fiscale inkomens op wijk- en sectorniveau?

### ISSUE THREAD

**Issue by anneliesvs** [provinciesincijfers/data-wishlist#31]
Zijn er plannen om de fiscale inkomens ook te ontsluiten op wijk- en sectorniveau?

**Comment by joostschouppe** [comment]
Voor zover deze aggregeerbaar zijn, zijn deze al sinds de start van de connector beschikbaar, zie https://provincies.incijfers.be/jive?workspace_guid=f0c08064-bb3a-4750-961a-2c700a8bee3e
We hebben wel nog steeds niet alle issues kunnen uitklaren ivm deze data die ons op maat opgeleverd worden door statbel
