### ISSUE TITLE
gegevens uit de IMA atlas

### ISSUE THREAD

**Issue by anneliesvs** [provinciesincijfers/data-wishlist#32]
Zijn er plannen om de gegevens van de IMA atlas ook te ontsluiten via de connector?
Wij hebben momenteel de vraag vanuit de eerste lijnszone Gent om een dashboard ELZ te maken.
Ze willen daarbij ook cijfers ontsluiten die momenteel op IMA staan.

**Comment by HildeC** [comment]
2 relevante zaken hierbij:

1. we proberen al jaren om IMA te overtuigen om een connector op te zetten. nu bevragen we hen buiten de atlas om, om data correct te kunnen opladen in PinC, wat extra werk met zich mee brengt. IMA heeft de connector niet afgewezen, maar omwille van tijdsgebrek wordt het steeds weer op de lange baan geschoven. ook is IMA nog niet 100% overtuigd dat een connector veiliger is dan over en weer via de mail, of afhalen van de ima-atlas, waarbij je toch ook ongesencureerde waarden te zien krijgt.
2. we zijn momenteel bezig met de opmaak van een rapport ELZ, op vraag van VIVEL. zou tegen eind van het jaar klaar moeten zijn.

**Comment by joostschouppe** [comment]
Niet op korte termijn dus. Maar Annelies, vraag gerust aan IMA of ze data op maat kunnen leveren, of eventueel een connector met ons willen opzetten
