### ISSUE TITLE
Woonvoorraad - woongelegenheden

### ISSUE THREAD

**Issue by BartDaemen** [provinciesincijfers/data-wishlist#33]
De cijfers van het aantal woongelegenheden (v2210_woonvoorraad) dalen bij update van gegevens (bijv. op 01/01/2019 van 45 515 --> 41 220. En bij laatste update (23/10) nog eens tot 40 660. 

Onze dienst Wonen is een oefening bezig met de cijfers en ziet de lagere cijfers verschijnen en vraagt nu hoe het verschil te verklaren is. Is er iets gewijzigd aan definitie of hoe kan daling verklaart worden? 

Merci alvast!

**Comment by joostschouppe** [comment]
We hebben dit concept inderdaad twee keer moeten aanpassen.
Het kadaster heeft vaak eigendommen met een woonfunctie NIET voorzien van een aantal wooneenheden. Uit onze analyses bleek dat bij dit soort gevallen toch vrij vaak effectieve bewoning werd vastgesteld. Daarom gaven we dit type zelf minstens het aantal 1 voor woongelegenheden.
In 2019 zijn er echter over heel Vlaanderen opeens 50.000 eigendommen opgedoken van dit type, die duidelijk NIET voor wonen bedoeld zijn.
In de eerste update hebben we deze er met een vrij specifieke regel eruit gegooid.
We hebben hier dan verder over nagedacht. Door de specifieke uitzondering werd de logica weeral een stap complexer - bovendien zou het kunnen dat het kadaster volgend jaar er weer net iets anders uitziet.
Daarom hebben we ervoor gekozen om de gehele regel om "indien woonfunctie, tel steeds minstens 1 woongelegenheid" geheel te laten vallen.
Deze wijzigingen hebben vooral impact op de cijfers van 2019, die dus in eerste instantie een onterecht stijging gaven.

@HildeC plant nog een overleg met de hele werkgroep kadaster (dus D&A+centrumsteden) waar we dit en andere wijzigingen kunnen bekijken.
