### ISSUE TITLE
werkenden tot op wijkniveau

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/data-wishlist#35]
vraag van Inge Lambrecht (Aalst)

> 
> We kregen van een collega bij kinderopvang de vraag of we tot op wijkniveau konden meegeven hoeveel jonge werkenden (tot 45j ongeveer) er zijn in Aalst. Ik stel vast dat we voor de NWWZ heel veel detail vinden, tot op wijkniveau. Voor de werkenden is het beperkt tot man/vrouw opsplitsing, en dit tot op stadsniveau. 
> 
> Klopt dit of zie ik dat verkeerd? Zo ja, welke is de reden daarvoor? Kunnen we op de één of andere manier aan die info geraken via jullie?
>

**Comment by VickyVB** [comment]
De NWWZ indicatoren zijn gebaseerd op  fijnmazige gegevens van de VDAB. Dit wil zeggen dat we geanonimiseerde gegevens hebben voor elke niet-werkende werkzoekende. Deze anonimisatie gebeurt op zo een manier dat we deze gegevens kunnen koppelen aan de (eveneens geanonimiseerde) rijksregistergegevens. Dit betekent inderdaad dat we de NWWZ kunnen lokaliseren tot op het niveau statistische sector en die vrij uitgebreid kunnen beschrijven (o.m. leeftijd, geslacht, werkloosheidsduur, opleidingsniveau, gezinssituatie).
De gegevens over de werkenden op PinC hebben de Vlaamse Arbeidsrekening als bron. De Vlaamse Arbeidsrekening is  dan weer gebaseerd op gegevens van RSZ, RSVZ, RVA, ... en deze gegevens zijn niet beschikbaar op een subgemeentelijk niveau zoals wijken. Je vindt hier wel indicatoren terug die een indeling maken naar geslacht, maar ook naar leeftijd, statuut (loontrekkend of zelfstandig) en sector van tewerkstelling.

Momenteel bereiden we een aanvraag bij de KSZ waarmee we zulke vragen in de toekomst wel kunnen beantwoorden binnen PinC. 

Momenteel kan je de gegevens die je collega nodig heeft ook downloaden van de KSZ website lokale statistieken
Hierbij alvast, per statsec van Aalst de werkenden tussen 18 en 45 op 31/12/2017
[werkenden_18-45_aalst statsec.xlsx](https://github.com/provinciesincijfers/data-wishlist/files/5554219/werkenden_18-45_aalst.statsec.xlsx)
Of je kan zelf hier een andere selectie maken: https://www.bcss.fgov.be/samilc/?language=nl

**Comment by inge-lambrecht** [comment]
Dankjewel @VickyVB voor de snelle hulp!
