### ISSUE TITLE
Cijfers over herkomst/bestemming verplaatsing (i.k.v. woon-werk pendel, shopgedrag detailhandel)

### ISSUE THREAD

**Issue by inge-lambrecht** [provinciesincijfers/data-wishlist#36]
Beste,

We vroegen ons af of de Provincie toegang heeft tot data met betrekking tot de herkomst/bestemming van verplaatsingen, meer bepaald woon-werk pendel en shopgedrag detailhandel.

Zo ja, kunnen we die via de Connector ook 'binnentrekken'? 

Dankjewel,
Inge

**Comment by joostschouppe** [comment]
Hoi Inge,
Wat we hebben:
- pendelmatrix onderwijs (relatie woonplaats/schoolplaats voor het leerplichtonderwijs)
- pendel bij loontrekkenden (instroom/uitstroom/saldo, geen matrix; weet niet goed of dat mogelijk is)
- gemodelleerde verkoopsstromen (matrix van wie waar geld uitgeeft aan verschillende types goederen)
- enquetegegevens fod mobiliteit (matrix, naar vervoersmiddel, op basis van HT-informatie van alle grotere bedrijven)

De matrixen zijn niet zo interessant voor de Connector, aangezien je dan alle informatie verliest over de gemeentegrenzen). Met je account op provincies.incijfers.be kan je wel al deze gegevens raadplegen. Misschien moet de werkgroep mobiliteit van OBMI eens een kort stukje schrijven ivm hoe ver je al springt (of niet) met deze data (cc @jorisvoets)
