### ISSUE TITLE
indicatoren erfgoed

### ISSUE THREAD

**Issue by anneliesvs** [provinciesincijfers/data-wishlist#37]
Zijn er plannen om erfgoed indicatoren te ontsluiten?

Onze dienst erfgoed zou graag erfgoed indicatoren op Gent in cijfers willen.
Hieronder het lijstje dat ze voorstellen.
ik vroeg me af of de provincie hier ook plannen voor heeft?

-	Aantal beschermde monumenten
-	Aantal en oppervlakte beschermde archeologische sites Is voor Gent momenteel één zone nl. Prinsenhof. Het ziet er wel niet direct naar uit dat daar nog iets bijkomt. 
-	Aantal en oppervlakte beschermde stads- en dorpsgezichten
-	Aantal en oppervlakte beschermde cultuurhistorische landschappen 
-	Oppervlakte archeologische zone Deze afbakening zal ook niet snel nog een aanpassing kennen.
-	Oppervlakte gebieden GGA (gebieden geen archeologie, wordt jaarlijks aangepast)
-	Aantal wetenschappelijke inventarisitems archeologisch – bouwkundig – landschappelijk – houtig erfgoed 
-	Aantal vastgestelde inventarisitems archeologisch – bouwkundig – landschappelijk – houtig erfgoed
-	Aantal goedgekeurde beheerplannen
-	Het aantal opgemaakte archeologienota’s voor Gent? (zowel intern als extern)

**Comment by joostschouppe** [comment]
Ja, er is een project in opstart rond dit thema. Ik vraag aan trekker Tanja om aan te vullen.

**Comment by TanjaTermote** [comment]
Dag Annelies
We starten donderdag met de werkgroep erfgoed. We bekijken daar een eerste lijst van mogelijke indicatoren. Ik zal de indicatoren die jullie voorstellen hier ook voorleggen. We hebben reeds bevestiging van het Agentschap Onroerend Erfgoed om data uit hun inventaris onroerend erfgoed per gemeente te ontsluiten in PinC. De meeste indicatoren van jouw lijstje kunnen uit deze inventaris gehaald worden. Daarnaast zullen we ook data van Monumentenwacht Vlaanderen ontsluiten en we bekijken met de werkgroep ook nog als er andere nuttige bronnen zijn.

**Comment by anneliesvs** [comment]
Dat is super! Ik ga ervan uit dat ik dan wel via de OBMI werkgroep op de hoogte word gehouden als de indicatoren ontsloten kunnen worden in de Connector.

**Comment by joostschouppe** [comment]
Dit project is nog steeds lopende.

**Comment by joostschouppe** [comment]
Er stroomt alvast een hoop data door via de connector. Als dit verder uitgebreid wordt, zal het ook in de connector komen.
