### ISSUE TITLE
Loop van de bevolking - migraties naar leeftijd

### ISSUE THREAD

**Issue by BartDaemen** [provinciesincijfers/data-wishlist#38]
Joost, 

Voor op het wensenlijstje. Kubus loop van de bevolking naar leeftijd. Of een aantal kernindicatoren van verhuisbewegingen naar leeftijd. Zijn hier vaak gevraagde cijfers ivm stadsvlucht / aantrekken 'jonge' gezinnen en veronderstel dat die vraag ook bij andere steden wel gedeeld wordt. 

Nu grijp ik vaak terug naar de[ interactieve cijfers](https://statistieken.vlaanderen.be/QvAJAXZfc/notoolbar.htm?document=SVR%2FSV-Demografie-LoopBevolking_fusie2019.qvw&host=QVS%40cwv100154&anonymous=true ) van statistiek Vlaanderen. Maar zou handig zijn om deze te kunnen combineren met andere gegevens in de databank.

Met vriendelijke groeten, 

Bart

**Comment by demaesschalckfilip** [comment]
@BartDaemen

Die cijfers staan al op PinC: onder loop van de bevolking staan twee kubussen: eentje met de bevolking op 01/01 (vanaf 1990) en eentje met de saldi (natuurlijk, buitenland, Wallonië, Brussel, andere Vlaamse gemeente, andere statsec binnen de gemeente). Die staan ook onderverdeeld naar leeftijd (naast nationaliteit, geboortenationaliteit, herkomst, geslacht). Optelling van de bevolking op 01/01 en alle saldi geeft de bevolking op 01/01 van het volgende jaar.

Beste groeten,
Filip

**Comment by BartDaemen** [comment]
Super interessant! Ik had het 'kenmerk' saldo nooit gevonden.
