### ISSUE TITLE
Verhoogde tegemoetkoming ziekteverzekering van huishoudens

### ISSUE THREAD

**Issue by dimitrivanbaelen** [provinciesincijfers/data-wishlist#4]
In Swing hebben we momenteel al heel wat gegevens over het aantal personen met een verhoogde tegemoetkoming in de ziekteverzekering.  Is het ook mogelijk om cijfers beschikbaar te maken op het niveau van huishoudens?

**Comment by StefanieWVL** [comment]
Ik vroeg vandaag na aan het IMA (onze bron voor deze data op PinC) of deze gegevens beschikbaar zijn naar huishoudtype (i.e. paar met kinderen, paar zonder kinderen, eenoudergezinnen, .... ) en naar herkomst.
Indien beschikbaar, dan kunnen deze zeker op Pinc beschikbaar gemaakt worden.

**Comment by HildeC** [comment]
in december 2022 heb ik nog eens de vraag gesteld aan IMA of er data mbt VT op gezinsniveau bestaat/beschikbaar kan gemaakt worden.
ik kreeg volgend antwoord:
momenteel hebben wij geen statistieken voor VT-gezin. 

Het lange antwoord:
Voor de atlas zijn indicatoren van VT per gezin te specifiek, dwz slechts een zeer beperkt aantal mensen zou hiermee aan de slag gaan en momenteel zijn we dus niet van plan om deze set van indicatoren uit te breiden. Moest hier in de toekomst meer vraag naar zijn, dan kan dit uiteraard opnieuw bekeken worden. 

het kan misschien een optie zijn om vanuit OBMI deze vraag aan IMA te stellen, om te benadrukken dat er wel degelijk vraag is naar dergelijke indicator
