### ISSUE TITLE
Woon-Schoolpendel | binnen gemeente

### ISSUE THREAD

**Issue by BartDaemen** [provinciesincijfers/data-wishlist#40]
Beste, 

Vanuit Dienst Onderwijs komt hier de vraag om schoolpendel binnen gemeente in kaart te brengen. In het verleden was Vicky daarmee bezig en ze bezorgde me al eens de gegevens tot op wijk/statsectorniveau.

Zijn er plannen om woon-schoolpendel tussen sectoren/wijken te ontsluiten? Of is het een optie om de gegevens opnieuw te krijgen?

Bedankt alvast!

**Comment by joostschouppe** [comment]
Ja, die kan je nog steeds aanvragen bij @VickyVB 
Vicky, inderdaad misschien wel een idee om dit nog eens te proberen, op wijkniveau deze keer.

**Comment by VickyVB** [comment]
@BartDaemen  dit zit inderdaad nog niet in PinC. Als je me precies laat weten welke kruisingen (kleuteronderwijs, lager onderwijs, secundair onderwijs) je wil kan ik je dit op korte termijn wel in een csv bezorgen.

**Comment by BartDaemen** [comment]
Hey Vicky, 

Graag 
- een opsplitsing tussen gewoon kleuteronderwijs - gewoon lager onderwijs - vgso
- met als 'van' / 'naar'-velden de stat.sectoren en wijken

Op manier die het je makkelijkste is om aan te leveren. Bij van en naar mogen ook de stat/wijken van andere gemeenten staan, zo heb ik beeld van iedereen die van buiten stad waar in Hasselt naar school gaat, en van iedereen die in stad woont en binnen stad of buiten stad schoolloopt.

Merci alvast!

Bart

**Comment by VickyVB** [comment]
@BartDaemen Het bestand is verzonden naar bart.daemen@hasselt.be.
