### ISSUE TITLE
verhuisbewegingen tussen wijken

### ISSUE THREAD

**Issue by anneliesvs** [provinciesincijfers/data-wishlist#41]
Is het mogelijk om de cijfer voor verhuisbewegingen ook tussen wijken te krijgen (parallel aan de indicatoren op sectorniveau):
binnen wijk
naar andere wijk
uit andere wijk

**Comment by joostschouppe** [comment]
Even meegeven dat Veerle Claes via e-mail (foei toch, Veerle :)) een gelijkaardige vraag stelde:

> Ik wil immigraties bekijken op wijkniveau, maar dit is niet mogelijk.
> Enkel gemeente of stat sec…
> https://stadsregioturnhout.incijfers.be/jive?workspace_guid=a20118d7-b8fc-4833-a27a-768beb073e8a
> Is zo voor de meeste onderwerpen in het deeltje verhuisbeweging.

@demaesschalckfilip : kan je in je volgende verwerking van deze data eens bekijken of het te doen is om dat mee te nemen?

**Comment by demaesschalckfilip** [comment]
Dat klopt, dat kan voorlopig niet, omdat immigraties en emigraties niet optelbaar zijn, en enkel ingeladen op niveau statsec en gemeente (en niet voor de tussenliggende niveau's). Ik bekijk of we dat kunnen meenemen bij de volgende verwerking.

Wat nu al wel kan is het saldo met de rest van de gemeente bekijken (saldi zijn immers wel optelbaar), op wijk- of deelgemeenteniveau, en dit via de saldi-kubus:

https://provincies.incijfers.be/jive?workspace_guid=f62cb021-b953-4613-a0f5-09e46b9efa19 (voorbeeld met wijken van Turnhout)

Je kan daar ook opsplitsen naar leeftijd, geslacht, nationaliteit...

**Comment by veerlecl** [comment]
Mea culpa @joostschouppe ! Ik zal mijn best doen om het voortaan rechtstreeks hier te posten
@demaesschalckfilip  alvast bedankt voor tussentijdse tip!

**Comment by joostschouppe** [comment]
Status gevraagd aan Filip

**Comment by joostschouppe** [comment]
Brede interesse hierin (op zijn minst Leuven, Hasselt, Roeselare, Genk, Oostende)

**Comment by demaesschalckfilip** [comment]
In orde, ik zal de cijfers ook berekenen en opladen op wijk- en deelgemeenteniveau (in december, als de meest recente wijkindelingen opgeladen zijn), te beginnen met de drie meest recente jaren.

Het gaat dan over immigraties van en emigraties naar andere Vlaamse gemeenten en andere Belgische gemeenten, en verder over migraties binnen de gemeente zelf: (1) het aantal migraties vanuit/naar een gebied (statistische sector, wijk, deelgemeente) naar/vanuit andere gebieden in de gemeente en (2) het aantal verhuisbewegingen binnen het gebied (statistische sector, wijk, deelgemeente, gemeente) zelf. De huidige variabele 'immigratie vanuit een andere statistische sector in de gemeente' wordt dan 'immigratie vanuit een ander gebied in de gemeente', de huidige variabele 'emigratie naar een andere statistische sector in de gemeente' wordt dan 'emigratie naar een ander gebied in de gemeente' en de variabelen 'migraties binnen de statistische sector' en 'migraties binnen de gemeente' worden dan één variabele: 'migraties binnen het gebied', beschikbaar op niveau statistische sector, wijk, deelgemeente en gemeente.

Alle andere variabelen zijn nu al beschikbaar op wijkniveau (want die zijn optelbaar).

**Comment by demaesschalckfilip** [comment]
Deze cijfers zijn vanaf maandag beschikbaar op PinC. Dat wil zeggen dat alle variabelen die op statsec niveau beschikwaar waren, dat nu ook zijn op niveau wijk en deelgemeente.
