### ISSUE TITLE
Voertuigenpark

### ISSUE THREAD

**Issue by mehtap19** [provinciesincijfers/data-wishlist#42]
Altijd interessant om [gegevens voertuigenpark ](https://statbel.fgov.be/nl/themas/mobiliteit/verkeer/voertuigenpark#figures) op gemeenteniveau ook op te nemen in provincies en uiteraard in de connector. Momenteel laden we ze manueel op in de eigen databank.

Merci!

**Comment by joostschouppe** [comment]
Dat is in scope van de data rond mobiliteit die we gaan verzamelen, zie https://github.com/provinciesincijfers/PinC-taakopvolging/issues/204

**Comment by joostschouppe** [comment]
Dit is inmiddels opgelost via https://github.com/provinciesincijfers/PinC-taakopvolging/issues/265
