### ISSUE TITLE
Demografie | timing actualisering

### ISSUE THREAD

**Issue by BartDaemen** [provinciesincijfers/data-wishlist#43]
Beste, 

De klassieke vraag : is er al een ruw zicht op wanneer de demografische cijfers op basis van het rijksregister geactualiseerd / beschikbaar zullen zijn?

Met vriendelijke groeten, 

Bart

**Comment by joostschouppe** [comment]
Zie https://github.com/provinciesincijfers/connectorbeheer/issues/45 :)
