### ISSUE TITLE
Verharding --> cijfers na de komma

### ISSUE THREAD

**Issue by BartDaemen** [provinciesincijfers/data-wishlist#48]
Hey Joost, 

Kan voor onderwerp dna_vp1592_opp_verharding de cijfers na de komma geactiveerd worden? Nu zijn het gehele getallen.

Merci alvast!

**Comment by joostschouppe** [comment]
Dag Bart,
Dit is een keuze in onderling overleg met de data-leverancier. Zeker op subgemeentelijk niveau is de data niet exact genoeg om cijfers na de komma te verantwoorden.
cc @valeriepirard
