### ISSUE TITLE
Dataset Sport Vlaanderen

### ISSUE THREAD

**Issue by BartDaemen** [provinciesincijfers/data-wishlist#49]
Hey, 

Sport Vlaanderen stelt heel wat data beschikbaar rond sport in elk van de Vlaamse gemeenten. Ook als open data https://www.sport.vlaanderen/kennisplatform/thema-open-data/ . Vanuit departement vrije tijd wil men meer cijfers opvolgen en nu wordt vaak teruggegrepen naar de set van  gemeentelijke sportindicatoren. In een ideale wereld zouden deze raadpleegbaar zijn via Hasselt.incijfers.be naast de andere omgevingsdata

Overwegen jullie om deze op te nemen in provincies.incijfers.be? Anders ga ik zelf aan de slag

Merci alvast!

Met vriendelijke groeten, 

Bart

**Comment by joostschouppe** [comment]
Bart, we hebben het hier al eerder over gehad. Ik kopieer je comment naar daar en sluit deze. Zie https://github.com/provinciesincijfers/data-wishlist/issues/7
