### ISSUE TITLE
inburgeringsdata gekoppeld aan verhoogde tegemoetkoming en/of leefloon

### ISSUE THREAD

**Issue by anneliesvs** [provinciesincijfers/data-wishlist#50]
Zijn er gegevens beschikbaar over inburgeraars gekoppeld aan verhoogde tegemoetkoming en/of leefloon?
Of kan ik deze gegevens ergens opvragen?

**Comment by joostschouppe** [comment]
Dit hebben we zeker niet, en het lijkt ons ook onwaarschijnlijk dat het ergens beschikbaar is
