### ISSUE TITLE
Detail personen met een handicap

### ISSUE THREAD

**Issue by anneliesvs** [provinciesincijfers/data-wishlist#53]
Hebben jullie toevallig gedetailleerde gegevens over personen met een handicap? 
We zijn specifiek op zoek naar het aantal doven/slechthorenden, het aantal blinden/slechtzienden, het aantal personen met een fysieke beperking.

**Comment by Tine-VB** [comment]
Ik denk niet dat dat ergens beschikbaar is. In het verleden ook al vaak naar gezocht. Ik zat ook in een werkgroep die onderzocht welke cijfers rond handicap er (zouden moeten) zijn. Dit is het eindrapport, maar dus: geen detailgegevens beschikbaar...
[20220321_SLAHandicap_rapportfinal.docx](https://github.com/provinciesincijfers/data-wishlist/files/9557684/20220321_SLAHandicap_rapportfinal.docx)
