### ISSUE TITLE
Km gereden per wagen

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/data-wishlist#54]
Misschien mogelijk via de keuringsdata

**Comment by HanneODB-VLBR** [comment]
Een interessante suggestie. Ik heb alvast contact opgenomen met Car-pass, een vzw die het register van de kilometerstanden van het Belgische wagenpark zou beheren. Ik agendeer ook op agenda voor volgende mobiliteitswerkgroep.

**Comment by HanneODB-VLBR** [comment]
Van car-pass vzw reactie gehad dat zij niet over eigenaarsgegevens beschikken en zodoende geen data op gemeenteniveau kunnen verstrekken. Daarnaast ook contact opgenomen met GOCA, koepel van keuringscentra, vooralsnog geen reactie ontvangen.

**Comment by HanneODB-VLBR** [comment]
Van GOCA bericht gekregen met de simpele boodschap 'wij hebben deze data niet'. Nog eens gekeken of MOW een optie zou zijn - Statistiek Vlaanderen baseert daar ook zijn cijfers over gereden km van gemotoriseerde voertuigen op - maar daar staat als methodologie het volgende beschreven: "PROMOVIA maakt voor zijn berekeningen gebruik van enerzijds de tellingen met tellussen die door de Vlaamse overheid worden uitgevoerd en anderzijds bepaalde resultaten van de provinciale verkeersmodellen. PROMOVIA propageert de tellingen, die slechts op een beperkt aantal locaties plaatsvinden, over het hele netwerk. Deze propagatie wordt uitgevoerd met behulp van de wegvakbelastingen vanuit de provinciale verkeersmodellen v3.6.1, die wel voor een volledig netwerk beschikbaar zijn. Vanaf 2017 zijn er enkel nog tellingen voor de snelwegen ter beschikking, waardoor de gerapporteerde voertuigkilometer voor de andere wegen slechts een extrapolatie zijn.". Dus al dit al kan worden berekend op gemeenteniveau, wat me vrij onwaarschijnlijk lijkt, zou het sowieso geen betrouwbare resultaten opleveren. Dus deze sporen lopen een beetje dood. Ik ga vanmiddag nog eens polsen op de mobiliteitswerkgroep, of als iemand van de D&A's nog een idee heeft dan hoor ik het graag. Maar indien niet, dan zal ik dit issue afsluiten.

**Comment by joostschouppe** [comment]
Klinkt alsof het niet zal lukken. Sorry @xivk :)
