### ISSUE TITLE
Wegenregister extracties: oa trage wegen, knooppuntendichtheid

### ISSUE THREAD

**Issue by VirgeSmetsStadAntwerpen** [provinciesincijfers/data-wishlist#56]
Dit is een parameter die we sinds 2018 in stad Antwerpen systematisch gebruiken. Om de bewandelbaarheid van de centrumsteden te vergelijken, zou het zeer nuttig zijn om deze indicator aan te maken, alsook % trage wegen (zit in wegenregister in het veld: MORF IN ( 'aardeweg', 'voetgangerszone', 'wandel- of fietsweg, niet toegankelijk voor andere voertuigen'). Vzw Trage wegen gebruiken ook deze indicatoren.

https://stadincijfers.antwerpen.be/Databank/Jive/?workspace_guid=c9ba3843-302b-4a04-9dac-1f36a46e4788

**Comment by joostschouppe** [comment]
Dubbel met https://github.com/provinciesincijfers/data-wishlist/issues/6#issuecomment-1274749979
