### ISSUE TITLE
Privaat groen: groenkaart Vlaanderen koppelen met kadaster

### ISSUE THREAD

**Issue by VirgeSmetsStadAntwerpen** [provinciesincijfers/data-wishlist#58]
Om privaat groen te berekenen: wordt om de 3 jaar de groenkaart Vlaanderen (2012, 2015, 2018,.. zie geopunt) zo bewerkt in GIS, door de bebouwing eruit te halen en te koppelen aan de kadastrale percelen, zie metadata: https://stadincijfers.antwerpen.be/Databank/Jive/?workspace_guid=4f337f97-a798-4c13-911d-0cfeb7a79a2f
% groene of onverharde oppervlakte van private woon-, economische en andere percelen t.o.v. totale oppervlakte van deze percelen.
Dit is het aandeel groene open oppervlakte van deze percelen t.o.v. totale oppervlakte van het gebied, dus zonder de bebouwing (volgens GRB- hoofd- en bijgebouwen), ofwel de onverharde, groene buitenruimte of tuin (voor- en achterkant van het perceel) (volgens Groenkaart Vlaanderen).
De percelen zijn opgedeeld volgens functie/ grondgebruik van het kadaster:
1. appartementsgebouwen en buildings (wonen)
2. huizen, hoeven en bijgebouwen (wonen)
3. industrie (economie)
4. opslag (economie)
5. kantoor (economie)
6. commercieel (economie)
7. ander (vaak gemeenschapsvoorzieningen)
8. onbebouwd (groen en parken)

Deze groenkaart is een raster (1m resolutie) van segmentatieclassificatie van de zomervlucht orthofoto’s in opdracht van het Agentschap voor Natuur en Bos (ANB) met de klassen “Niet groen”, “Landbouw”, “Laag Groen” (minder dan 3m) en “Hoog Groen” (meer dan 3m), die om de 3 jaar worden aangemaakt sinds 2012.
En werkwijze:
1.	Bewerken van raster naar polygon: Groenkaart Vlaanderen OMZETTEN Raster naar Integer: Spatial Analyst Tools/Math/Int (codes 1 en 2 zijn groen)
2.	INTERSECT groen met niet bebouwing (percelen ERASE  bebouwing_toestand20220101_perceel, output feature class: niet_bebouwing_perceel_toestand20220101
3.	groen_2018_nietbebperceel_2019: DISSOLVE naar capakey (anders te veel records om weg te schrijven als dbf (295.000 = teveel, beter 95.481) en voeg velden toe "groenopp_ortho" (Long Integer) = Calculate Fields = Shape Area, "NIS_hfdgroep" (txt 50), "statsec_code" (txt 10), 
4.	KOPPEL deze laag ahv tabel veld capakey met sdedgeo.LAAG.KADASTER_PERCEEL_GEBRUIK en Calculate Fields functies en statsect-code en schrijf deze tabel weg

**Comment by joostschouppe** [comment]
Opvolging via https://github.com/provinciesincijfers/kadaster-post-processing/issues/20

**Comment by VirgeSmetsStadAntwerpen** [comment]
We berekenen ook het totale opp hoog groen uit Groenkaarten Vlaanderen.
Dit is de belangrijke 3-**30**-300 regel, 30% 
30-Klimaatgroen (zijn, fysieke gezondheid): min. 30% groen (hoog en de helft van laag groen)
