### ISSUE TITLE
% alleenwonende inwoners uitdovend?

### ISSUE THREAD

**Issue by BartDaemen** [provinciesincijfers/data-wishlist#59]
Beste, 

Ik merkte dat onderwerp "vp1114a_alleenw" (% alleenwonend t.o.v. alle inwoners) uitdovend geworden is? 
Is dat een bewuste keuze? Begrijp niet goed waarom. Is een vaak gevraagd onderwerp.

Is zo ook opgenomen in de themaboom op provincies.incijfers.be.  Als ik dit onderwerp moet verwijderen, vrees ik dat mensen tabellen en grafieken bouwen (alle inwoners naar positie in huishouden) die niet sommeren tot de 100%, wat verwarrend is. 

![afbeelding](https://user-images.githubusercontent.com/45167136/218781683-58564f6a-676c-467c-bfa4-3a550954e205.png)

Merci alvast!

Bart

**Comment by joostschouppe** [comment]
Dag Bart,
Dat is een vergissing geweest. Dit is net rechtgezet en stroomt dus dit weekend terug door.
Wat nu wél is aangepast, is dat v1114a_alleenw uitdovend wordt, omdat dit exact hetzelfde is als v1115a_alleenw . Waar dat eerste voorkomt, moet het dus vervangen worden door het tweede.
