### ISSUE TITLE
Verborgen waarden bij % alleenstaanden

### ISSUE THREAD

**Issue by BartDaemen** [provinciesincijfers/data-wishlist#60]
Beste, 

In provincies.incijfers.be krijg ik bij onderwerp "% alleenwonend (t.o.v. bevolking)" enkel verborgen waarden te zien. Gaat om onderwerp "vp1114a_alleenw". Loopt er iets mis met de drempelwaarden?

![afbeelding](https://github.com/provinciesincijfers/data-wishlist/assets/45167136/e03b1e1c-e1e2-4c93-9f4e-f68fe5262c8d)

Met vriendelijke groeten, 
Bart Daemen

**Comment by VickyVB** [comment]
@rudymarynissen  Kan jij dit even bekijken? Dit geeft ook problemen in het rapport bevolking en huishoudens.

**Comment by rudymarynissen** [comment]
Zou in orde moeten zijn in de test versie. Treshold indicator was fout.
