### ISSUE TITLE
Afval

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/data-wishlist#8]
Alle afvalcijfers (zowel huishoudelijk als bedrijfsmatig) zijn jaarlijks verplicht aan te geven bij OVAM en dus wellicht beschikbaar. 
OVAM heeft normaal gezien alle cijfers voor de gemeenten van het Vlaams Gewest. (zie https://www.ovam.be/afval-materialen )

belangrijkste cijfers : opsplitsing van selectief (=gesorteerd) en niet-selectief (=restafval+grof afval) 
misschien zouden we wel "zwerfvuil" kunnen uitlichten

Oorspronkelijke vraag: Jerome Jansen van ecowerf.be

**Comment by joliendeboodt** [comment]
Vandaag kreeg ik de vraag (via onze directeur van Den Azalee/kringwinkel) om cijfers op te nemen in Stad in cijfers over hergebruik, selectief ingezameld afval (recyclage), ... kortom de cijfers die steden, kringwinkels, recyclageparken, ... zelf jaarlijks aan OVAM moeten bezorgen.
We maken een intern dashboard rond indicatoren (voor opvolging meerjarenplan), waar thema afval niet mag ontbreken. De cijfers van OVAM zouden dus zeer welkom zijn.

**Comment by joostschouppe** [comment]
Ook in opleiding van Tine is hier naar gevraagd.

Oorspronkelijke vraag van Jerome:

Onderwerp: Betr.: RE: Vraag vanop Provincies in Cijfers
Dag Joost, 
Mijn belangrijkste reden was eigenlijk dat als jullie de cijfers over thema's zoals Klimaat, Mobiliteit en Energie beschikbaar dan mogen de cijfers over Milieu niet ontbreken. 
En aangezien afval toch een groot aandeel in het thema Milieu heeft en ze ook nog eens beschikbaar zijn op gemeentelijk niveau, is dit van groot belang om een zo breed mogelijk beeld te geven aan de al degenen die met deze cijfers analytisch tewerk gaat. 
Alle afvalcijfers (zowel huishoudelijk als bedrijfsmatig) zijn jaarlijks verplicht aan te geven bij OVAM en dus ook beschikbaar volgens mij. 
OVAM heeft normaal gezien alle cijfers voor de gemeenten van het Vlaams Gewest. 
belangrijkste cijfers zouden kunnen zijn : opsplitsing van selectief (=gesorteerd) en niet-selectief (=restafval+grof afval) afvalstromen in vergelijking met de Belfius clusters en/of uitrustingsniveau van de gemeente. 
een suggestie : misschien zouden we wel "zwerfvuil" kunnen uitlichten om via deze weg wat meer te kunnen sensibiliseren.

**Comment by joostschouppe** [comment]
@joliendeboodt : iemand van OVAM (Willem Raes) en iemand van VVSG (Eva Gijsegom, Projectmedewerker Lerende Netwerken Afvalbeleid) vragen dit nu ook. Op het eerste gezicht gaat het echter maar om een indicator of twee. In jouw oorspronkelijk bericht lijkt dit veel uitgebreider te kunnen?

**Comment by joostschouppe** [comment]
Online te raadplegen data (@StefanJacques ):

> De hoeveelheden restafval (2013-2018) en de doelstellingen vind je terug op onze website: https://www.ovam.be/inventarisatie-huishoudelijke-afvalstoffen.
> Op 10/12/2020 zullen de gegevens voor 2019 beschikbaar zijn.

De relevante cijfers zijn te vinden in https://www.ovam.be/sites/default/files/atoms/files/Data_huishoudelijk_afval_2013-2018.xlsx , tabblad "bijlage 7.3" met indicatoren:
Restafval in kg/inw   2013
…
Restafval in kg/inw 2018
Inwoners aantal 2018
Restafval in    ton 2018
Doelstelling in kg/inw 2022

Dat is niet ideaal voor de periode 2013-2017, aangezien we dan op basis van een weging van een afgerond getal de totalen per provincie etc gaan berekenen. Dus best de totalen opvragen.
De Doelstelling is voor 2022. Die zouden we eventueel voor alle jaren vanaf 2013 kunnen inlezen, zodat je een platte lijn krijgt waar de werkelijke lijn dan hopelijk naartoe evolueert.

>

**Comment by joliendeboodt** [comment]
Volgende zijn de op te volgen indicatoren voor opvolging van ons meerjarenplan: restafval per inwoner (in ton + aantal kg restafval per inwoner), recyclage (in ton + aantal kg selectief ingezameld afval per inwoner), hergebruik (aantal kg hergebruik per inwoner).

Voor selectief ingezameld afval: opsplitsing per afvaltype (PMD, glas, ...) - ton + kg/inwoner.

**Comment by joostschouppe** [comment]
Staat al een tijd online
