### ISSUE TITLE
ruimteboekhouding & gewestplan

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/data-wishlist#9]
inhoudelijk: datakwaliteit
organisatorisch: overleggen met Vlaamse overheid

**Comment by mehtap19** [comment]
@joostschouppe zou het kunnen dat ik hier niet direct 'een' specifiek antwoord op de vraag mbt bevolkingsdata 2020 terugvind?

**Comment by joostschouppe** [comment]
Heb je manueel nummer 9 overgetikt? Als je gewoon op de link klikt, dan zou je moeten terecht gekomen zijn in https://github.com/provinciesincijfers/connectorbeheer/issues/9

**Comment by joostschouppe** [comment]
afgerond
